### ISSUE TITLE
Thin-plate splines (warp field estimates from features)

### ISSUE THREAD

**Issue by nfaggian** [pyimreg/python-register#10]
We can make the non-linear warp using salient features (reasonably) well using thin plate splines.

Refer to:

http://en.wikipedia.org/wiki/Thin_plate_spline

RegisterData should be extended to include features required for spline fitting - point features or line constraints come to mind.

**Comment by nfaggian** [comment]
Made a ThinPlateSpline branch - might need a code review of this work.

The fast fitting is a bit of mind bending numpy.

**Comment by riaanvddool** [comment]
I am very much interested in feature based registration as well. I think it will be fast. Can also contribute a Haar wavelet salient feature finder. C++ code.

**Comment by riaanvddool** [comment]
I have added my code to the ThinPlateSpline branch but cant get it to run properly. Fails to find the library or something.

**Comment by nfaggian** [comment]
I think you made a new branch actually ;)

**Comment by riaanvddool** [comment]
oh, sorry

**Comment by nfaggian** [comment]
No drama - did you see the idea about consolidating the c++ code. I think its a good idea to put it all in an Extern directory

**Comment by riaanvddool** [comment]
Yes, i agree. Less duplication.

**Comment by riaanvddool** [comment]
I struggling with the Haar code. Getting a segmentation fault somewhere.

**Comment by nfaggian** [comment]
I can imagine that it is really hard to debug c++ code exposed to python. 

Maybe a good starting point is to use the gdb server?

http://davis.lbl.gov/Manuals/GDB/gdb_17.html

**Comment by nfaggian** [comment]
Got the code more or less working now, just cleaning up tests. Managed to vectorize the code - interesting:

Vectorized : 100x100 image - 14.536 ms
Untouched : 100x100 image - 2505.894 ms

**Comment by nfaggian** [comment]
Performing a merge of this feature into master.
- Added a working exampe (requires pyYAML)
- Added a system and unit test for the code in test_register_features.
- All tests passed in the feature branch.

**Comment by nfaggian** [comment]
I think there is more work to do here:

1) features should be more flexible in their definition

2) split apart the linear and non-linear components

3) Generalize the feature registrator to make the thin-plate-spline deformation model

**Comment by nfaggian** [comment]
Making more commits to the feature branch slowly - attending pycon and moving house has really slowed me down.
