### ISSUE TITLE
No recovery from bad steps.

### ISSUE THREAD

**Issue by riaanvddool** [pyimreg/python-register#12]
The current Register.register method will never recover from a bad optimizations step. 

It needs to be investigated if this is just an implementation error.

The dampening is currently changed on a bad step, but this does not currently affect the warp that is applied before retesting.

**Comment by nfaggian** [comment]
Did we get anywhere with this?  I can spend some time on this tomorrow..

**Comment by riaanvddool** [comment]
I havnt spent time on it yet.

On Wed, Aug 3, 2011 at 12:28 PM, nfaggian
reply@reply.github.com
wrote:

**Comment by nfaggian** [comment]
Thanks to Riaan - I have made a branch "ticket_0012" with a fix to register.py for review. Begs the question how to test this???

**Comment by riaanvddool** [comment]
I found testing corner cases quite helpful in this case. Ie, try to register two identical images. Also, check the values of p returned by the register function versus what the last good step was.

**Comment by nfaggian** [comment]
ok

**Comment by nfaggian** [comment]
I think we have addressed this in issue_26
