### ISSUE TITLE
Consolidate c/c++ extensions

### ISSUE THREAD

**Issue by nfaggian** [pyimreg/python-register#16]
It looks like we have a bit of c code now.  As a result I would like to try and consolidate the c-extensions and have one exposed library, for example:

Register/
    Extern/
        Sampler.cpp
        Feature.cpp

If for some reason the libraries cannot be compiled the code should drop back to a python implementation or raise an error.

**Comment by riaanvddool** [comment]
I no longer have any c++ code in the feature module.

**Comment by nfaggian** [comment]
If we keep all c-code to the samplers then I think this task is no longer necessary.
