### ISSUE TITLE
Making things fast

### ISSUE THREAD

**Issue by riaanvddool** [pyimreg/python-register#19]
What do you guys think about using Theano to bring in GPU capability?

http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by nfaggian** [comment]
I support this - perhaps as a long lived branch. One thing we shouldn't loose sight of is getting the core methods work solid before we start to optimize.

**Comment by nfaggian** [comment]
I also want to push as much as possible a low number of dependencies for this code - which would help people just pick up and use it.

**Comment by riaanvddool** [comment]
I agree, we could possibly do a sprint to speed things up if needed later, like we discussed.
