### ISSUE TITLE
Add projective model

### ISSUE THREAD

**Issue by riaanvddool** [pyimreg/python-register#22]
The affine is a special case of homography. Projective model would include all 9 parameters of the homography.

**Comment by riaanvddool** [comment]
This is ready for merging to master. Nathan will you check and merge please?

**Comment by riaanvddool** [comment]
On ticket_0022 branch.

**Comment by stefanv** [comment]
I don't see the pull request, but I'd like to review the code once it comes in.

Just a technical detail: the homography is accurate up to scale, so there are 8 free parameters.

**Comment by riaanvddool** [comment]
I discussed with Nathan the fact that in order to generate pull requests, I will have to fork. So I think the consensus was that the 3 of us may work directly on Nathan's repo, other contributers must fork and submit pull requests until we trusts them. :)

**Comment by riaanvddool** [comment]
So the code for this issue is ready for review on branch: ticket_0022

**Comment by stefanv** [comment]
Forking the repository before working on it is probably a good idea.  It is easy enough to push straight into the main repo from your own repo.  The pull request review mechanism on GitHub is very useful, and I recommend we make use of it.  E.g., take a look here:

https://github.com/scikits-image/scikits.image/pull/19

Also click on the "Diff" and "Commits" buttons at the top.  This is perfect for line-by-line commentary and discussions on changes.

(I don't have the ability to comment on ticket_0022 branch, and I can't see easily what was changed--which means that I most likely will need to fetch that branch and manually inspect it before I can review, and then I'll have to manually add the comments here, without being able to refer to specific lines, etc.).

**Comment by nfaggian** [comment]
Lets all shift to pull requests - its easier to manage with github. 

I have just made a pull request for the branch - it seems like it is very easy to do this. Please let me know how it goes for you both, as far as I can tell you both should be able to see the request.

**Comment by riaanvddool** [comment]
Works well!

R

On Tue, Sep 20, 2011 at 2:21 PM, Nathan Faggian
reply@reply.github.com
wrote:

**Comment by riaanvddool** [comment]
Merged.
