### ISSUE TITLE
Resampler changes

### ISSUE THREAD

**Issue by nfaggian** [pyimreg/python-register#31]
Would like to add a bilinear resampler, perhaps also at some point some of the others listed here:

http://www.imgfsr.com/ResamplingCVPR.pdf

**Comment by nfaggian** [comment]
branched.

**Comment by nfaggian** [comment]
%timeit nearest.f(image.data, warp)
100 loops, best of 3: 2.79 ms per loop

%timeit cubic.f(image.data, warp)
10 loops, best of 3: 168 ms per loop

%timeit bilinear.f(image.data, warp)
100 loops, best of 3: 7.55 ms per loop

%timeit spline.f(image.data, warp)
10 loops, best of 3: 52.1 ms per loop

image.data.shape
Out[18]: (512, 512)

**Comment by nfaggian** [comment]
Can someone please look at this code for me - seems to be a little bit off. Probably a small detail - the linreg example falls over very quickly.

**Comment by riaanvddool** [comment]
I am missing MTF resampling in the list of resamplers.

**Comment by riaanvddool** [comment]
$ time python linreg_pyramid.py > cc.log
real        0m43.332s
user        0m42.420s
sys        0m0.800s

$ time python linreg_pyramid.py > spline.log

real        0m24.468s
user        0m23.620s
sys        0m0.760s
almost a x2 speedup!
(i commented the plot.show() line out)
