### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by hgrecco** [pyimreg/python-register#45]
Hi,

It would be very nice if you could package dist and put it in pypi. I will simplify distributing packages that have python-register as dependent. In addition, why there is another repo called imreg? Is just a historical artifact? Which one should I use?

**Comment by nfaggian** [comment]
Hi,

The project is in a state of transition at the moment. You probably would have noticed a significant change to both python-register and pyimreg.

The package should be "pyimreg"  which is what I want to clean up and get into pypi soon -- hopefully the coming weeks. 

Are you using any of the non-linear registration code? If so, that is no longer in the first expected release. I plan to try and slowly improve the code adding a proper implementation of the nonlinear registration and then shifting the code to use more building blocks from scikit-image. 

Cheers,

Nathan.

**Comment by hgrecco** [comment]
Hi Nathan,

Really good news. I am just using affine and shift for the moment. Basing thing on scikit-image is a great idea. Have looked at numba as a way of avoid writing C-code? It worked really good for me.

cheers
