### ISSUE TITLE
Explore optical flow for image registration

### ISSUE THREAD

**Issue by nfaggian** [pyimreg/python-register#6]
Consider optical the optical flow between two images as the non-linear deformation - it can be implemented as a non-linear registration algorithm.

This paper looks good:

High Accuracy Optical Flow Estimation Based on a Theory for Warping Thomas Brox, Andrés Bruhn, Nils Papenberg, Joachim Weickert (2004) Computer VisionECCV 2004 3024 p. 25-36

**Comment by stefanv** [comment]
Two quick ways of getting this done:

1) Extend the scikits-image OpenCV wrapper
2) Use the OpenCV python wrapper directly (don't think this option handles numpy arrays)

http://opencv.willowgarage.com/documentation/c/video_motion_analysis_and_object_tracking.html

**Comment by nfaggian** [comment]
Sounds good to me - have to look at how this tracks with the paper, but certainly would be a good start.

If we implemented this I would like an interface (layer of indirection to opencv), which can point to the opencv implementation if it is available (installed) otherwise point to a pure numpy version.

**Comment by nfaggian** [comment]
Not sure if this is something we need to do anymore - should probably just focus on getting the cubic spline model working as well as possible.
